"""The web side of the huckepack modes: one descriptor, one snapshot, no storage.

Three things happen here and nothing else:

1. the browser asks what kind of installation this is (``GET /huckepack/mode``);
2. it hands its database in and takes it back out (``/huckepack/session``);
3. every request carries a session token and — in ``huckepack-only-host`` — a
   key, both of which are bound for the request and dropped at its end.

The session token is generated by the browser and must look like a token: at
least 22 characters of URL-safe alphabet. It addresses an in-memory database,
so a guessable token would be a way to read someone else's running session.
"""

from __future__ import annotations

import json
import re
from typing import Any, Dict

from fastapi import FastAPI, Request, Response
from fastapi.responses import HTMLResponse, JSONResponse

from . import huckepack_key, huckepack_storage
from .server_mode import ServerMode, current_mode, describe_mode

SESSION_HEADER = "X-Huckepack-Session"
SNAPSHOT_MEDIA_TYPE = "application/vnd.sqlite3"
TOKEN_PATTERN = re.compile(r"^[A-Za-z0-9_-]{22,128}$")

#: Paths that answer even when the mode is the ``pay-membership`` stub, so the
#: interface can explain the situation instead of showing a blank error.
STUB_ALLOWED_PREFIXES = ("/static/", "/huckepack/mode")


def _valid_token(raw: str | None) -> str | None:
    if raw and TOKEN_PATTERN.match(raw):
        return raw
    return None


def install(app: FastAPI) -> None:
    """Add the huckepack middleware and endpoints to an application."""

    @app.middleware("http")
    async def huckepack_context(request: Request, call_next):
        mode = current_mode()

        if not mode.implemented and not request.url.path.startswith(STUB_ALLOWED_PREFIXES):
            return _stub_response(mode)

        session_reset = huckepack_storage.bind_session(
            _valid_token(request.headers.get(SESSION_HEADER))
        )
        key_reset = huckepack_key.bind_request_key(
            request.headers.get(huckepack_key.KEY_HEADER) if mode.key_from_browser else None
        )
        try:
            return await call_next(request)
        finally:
            huckepack_key.unbind_request_key(key_reset)
            huckepack_storage.unbind_session(session_reset)

    @app.get("/huckepack/mode")
    async def huckepack_mode() -> JSONResponse:
        return JSONResponse(mode_payload())

    @app.put("/huckepack/session")
    async def huckepack_session_load(request: Request) -> Response:
        guard = _require_browser_mode()
        if guard is not None:
            return guard
        token = _valid_token(request.headers.get(SESSION_HEADER))
        if token is None:
            return JSONResponse({"error": "missing_session_token"}, status_code=400)
        blob = await request.body()
        try:
            huckepack_storage.SESSIONS.load(token, blob)
        except huckepack_storage.SnapshotError as exc:
            return JSONResponse({"error": "bad_snapshot", "detail": str(exc)}, status_code=400)
        return JSONResponse({"loaded": True, "bytes": len(blob)})

    @app.get("/huckepack/session")
    async def huckepack_session_snapshot(request: Request) -> Response:
        guard = _require_browser_mode()
        if guard is not None:
            return guard
        token = _valid_token(request.headers.get(SESSION_HEADER))
        if token is None:
            return JSONResponse({"error": "missing_session_token"}, status_code=400)
        blob = huckepack_storage.SESSIONS.snapshot(token)
        return Response(
            content=blob,
            media_type=SNAPSHOT_MEDIA_TYPE,
            headers={"Cache-Control": "no-store"},
        )

    @app.delete("/huckepack/session")
    async def huckepack_session_drop(request: Request) -> Response:
        guard = _require_browser_mode()
        if guard is not None:
            return guard
        token = _valid_token(request.headers.get(SESSION_HEADER))
        if token is None:
            return JSONResponse({"error": "missing_session_token"}, status_code=400)
        huckepack_storage.SESSIONS.drop(token)
        return JSONResponse({"dropped": True})


def receipt_script_tag(payload: Dict[str, Any]) -> str:
    """Hand a finished result to the browser so it can write the receipt file.

    A ``<script type="application/json">`` block, not a data attribute: the
    payload contains a transcript, and attribute escaping is the wrong place to
    be clever. ``</`` is neutralised because that is the one sequence that
    could end the block early.
    """
    body = json.dumps(payload, ensure_ascii=False).replace("</", "<\\/")
    return f'<script type="application/json" id="huckepack-receipt">{body}</script>'


def mode_payload() -> Dict[str, Any]:
    """The descriptor plus the names the browser needs to talk to this server."""
    payload = describe_mode()
    payload["session_header"] = SESSION_HEADER
    payload["key_header"] = huckepack_key.KEY_HEADER
    payload["snapshot_url"] = "/huckepack/session"
    return payload


def _require_browser_mode() -> Response | None:
    mode = current_mode()
    if mode.stores_in_browser:
        return None
    return JSONResponse(
        {
            "error": "not_applicable",
            "mode": mode.value,
            "detail": "This installation stores on the host; there is no browser snapshot.",
        },
        status_code=409,
    )


def _stub_response(mode: ServerMode) -> HTMLResponse:
    return HTMLResponse(
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<title>Not available</title></head><body>"
        f"<h1>Server mode {mode.value} is a placeholder</h1>"
        "<p>This mode would need accounts, billing and server-side storage. "
        "None of that is built. Start the server with "
        "<code>local</code>, <code>huckepack-gift</code> or "
        "<code>huckepack-only-host</code>.</p></body></html>",
        status_code=503,
    )
